// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "730ed34a-ab3f-405e-aba4-c1e2324fe1f5");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575351512);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575351632);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575358253);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575351272);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575351152);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575351392);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575351872);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575351752);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 798720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575351003);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8cf413e7-7437-40cb-9f5d-9341823be436}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575273600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575369894400");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575371701400");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575358261945");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575361861945");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575351032");
user_pref("browser.slowStartup.averageTime", 28906);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575351037671");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "ed2f9952270948ed9d6320da9969effb");
user_pref("extensions.blocklist.lastModified", "Mon, 02 Dec 2019 11:14:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575351516);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"aba36414-252e-4b76-b790-6340369b95d1\",\"screenshots@mozilla.org\":\"88b9db8f-6399-4c35-85e5-477d967969e0\",\"webcompat-reporter@mozilla.org\":\"1d532780-1721-458f-b296-0a64703f3493\",\"webcompat@mozilla.org\":\"5905e3e0-5db4-48ad-9f04-e8f084df5442\"}");
user_pref("idle.lastDailyNotification", 1575352047);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575351067);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575351066);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575352048);
user_pref("places.history.expiration.transient_current_max_pages", 57642);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "309c28f6-430b-4048-bd1f-dcc0eebfcbc8");
user_pref("security.sandbox.plugin.tempDirSuffix", "3f19ceb9-45b2-4727-a2ac-75d03dcd5e8b");
user_pref("services.blocklist.addons.checked", 1575351090);
user_pref("services.blocklist.gfx.checked", 1575351090);
user_pref("services.blocklist.onecrl.checked", 1575351090);
user_pref("services.blocklist.pinning.checked", 1575351090);
user_pref("services.blocklist.plugins.checked", 1575351090);
user_pref("services.settings.clock_skew_seconds", -46);
user_pref("services.settings.last_update_seconds", 1575351438);
user_pref("services.settings.main.language-dictionaries.last_check", 1575351090);
user_pref("services.settings.main.sites-classification.last_check", 1575351090);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575352048);
user_pref("toolkit.startup.last_success", 1575350996);
user_pref("toolkit.telemetry.cachedClientID", "8d61a1eb-8fce-4a5c-9c3d-3293a1a92a77");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
